### ISSUE TITLE
FEZ autosplitter sometimes stops detecting room changes

### ISSUE THREAD

**Issue by thearst3rd** [jbzdarkid/Autosplitters#19]
Hi darkid, I tried sending you a Discord DM before creating an issue, but it looks like you're not accepting DMs or friend requests at the moment. Regardless, a GitHub issue works too.

I've been running FEZ recently and I've been using your autosplitter. For a while, it was working flawlessly, but recently I've been having an issue where it sometimes doesn't automatically detect splits. It seems to be more likely to happen when I am using OBS and such, as when I was doing some off-stream testing everything was working perfectly. But twice now when streaming, it stops automatically detecting room changes/splits.

I've downloaded DebugView to be able to read the script's print statements (this tool seems ancient, if you know of anything better please let me know). When I start a run, it reports the level changes for a short bit, but at some point the level changes stop being detected. I'm not sure what the issue is and I'm still trying to look into it. Let me know if you've seen this before and know some ways to mitigate it.

Thanks!

**Comment by jbzdarkid** [comment]
Lost track of this, sorry -- pushed an update which has some updates. My guess/worry is that the pointer path is dying, so a more accurate pointer path would be the fix.

**Comment by jbzdarkid** [comment]
Fixed in #23
